//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblestudiante
    {
        public tblestudiante()
        {
            this.tblAsesor_estudiante = new HashSet<tblAsesor_estudiante>();
            this.tblautoaprendizajes = new HashSet<tblautoaprendizaje>();
            this.tblconocimiendoRelacionadoes = new HashSet<tblconocimiendoRelacionado>();
            this.tblconocimientotrabajoes = new HashSet<tblconocimientotrabajo>();
            this.tblEmpresa_estudiante = new HashSet<tblEmpresa_estudiante>();
            this.tblEstudianteEstudios = new HashSet<tblEstudianteEstudio>();
            this.tblestudianteotrosconocimientoes = new HashSet<tblestudianteotrosconocimiento>();
        }
    
        public int EstudianteId { get; set; }
        public string EstudianteCod { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public int NacionalidadId { get; set; }
        public int FacultadId { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public byte[] Imagen { get; set; }
        public string HojaVida { get; set; }
        public string Perfil { get; set; }
    
        public virtual ICollection<tblAsesor_estudiante> tblAsesor_estudiante { get; set; }
        public virtual ICollection<tblautoaprendizaje> tblautoaprendizajes { get; set; }
        public virtual ICollection<tblconocimiendoRelacionado> tblconocimiendoRelacionadoes { get; set; }
        public virtual ICollection<tblconocimientotrabajo> tblconocimientotrabajoes { get; set; }
        public virtual ICollection<tblEmpresa_estudiante> tblEmpresa_estudiante { get; set; }
        public virtual tblnacionalidad tblnacionalidad { get; set; }
        public virtual ICollection<tblEstudianteEstudio> tblEstudianteEstudios { get; set; }
        public virtual tblfacultad tblfacultad { get; set; }
        public virtual ICollection<tblestudianteotrosconocimiento> tblestudianteotrosconocimientoes { get; set; }
    }
}
