//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblestudianteotrosconocimiento
    {
        public int ConocimientoId { get; set; }
        public int EstudianteId { get; set; }
        public string ProyectoPresente { get; set; }
        public string ProyectoFuturo { get; set; }
        public string ProyectoPasado { get; set; }
    
        public virtual tblestudiante tblestudiante { get; set; }
    }
}
