//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresa_estudiante
    {
        public int RelacionEEId { get; set; }
        public int EstudianteId { get; set; }
        public int CentroPracticaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
    
        public virtual tblcentropractica tblcentropractica { get; set; }
        public virtual tblestudiante tblestudiante { get; set; }
    }
}
