//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfacultad
    {
        public tblfacultad()
        {
            this.tblasesors = new HashSet<tblasesor>();
            this.tblestudiantes = new HashSet<tblestudiante>();
            this.tblprogramas = new HashSet<tblprograma>();
        }
    
        public int FacultadId { get; set; }
        public string Facultad { get; set; }
    
        public virtual ICollection<tblasesor> tblasesors { get; set; }
        public virtual ICollection<tblestudiante> tblestudiantes { get; set; }
        public virtual ICollection<tblprograma> tblprogramas { get; set; }
    }
}
